#jte.stages.creativ()
jte.libraries.rhinos.build_mute() 
jte.libraries.gradle.build_mute()

//pipeline {
//    agent any
//    stages {
//        stage('INIT') {
//            steps {
//                //jte.libraries.maven.unit_test()
//                //jte.libraries.rhinos.build_mute()
//                build_mute()
//            }
//        }
//    }
//}
//
//
